### ISSUE TITLE
Download Get-a-key Certificate error

### ISSUE THREAD

**Issue by picanl** [tmunzer/get-a-key#5]
Getting the following error when clicking the "Download Get-a-Key Certificate" 

Oups... There is a undefined error...
Unable to render undefined
ENOENT: no such file or directory, stat '/app/certs/5b4710925XXXXX0078495ab.mijnwifikey.piuscanisius.nl.xml'
Error: ENOENT: no such file or directory, stat '/app/certs/5b4710XXXXXX100078495ab.mijnwifikey.piuscanisius.nl.xml'
Sorry... I don't have any other information...

i have commented some out with XXXX 

any idea?

**Comment by tmunzer** [comment]
This issue has been fixed.
